# Generated by Django 2.2.12 on 2022-12-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_fakulteta', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Mjesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postanski_broj', models.PositiveIntegerField()),
                ('naziv_mjesta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Smjer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smjera', models.CharField(max_length=70)),
                ('smjer_fakultet', models.ManyToManyField(to='main.Fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Sveuciliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_sveucilista', models.CharField(max_length=50)),
                ('sveuciliste_postanski_broj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_studenta', models.CharField(max_length=20)),
                ('prezime_studenta', models.CharField(max_length=30)),
                ('jmbag_studenta', models.IntegerField()),
                ('email_studenta', models.EmailField(blank=True, max_length=70, unique=True)),
                ('student_fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fakultet')),
                ('student_postanski_broj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto')),
                ('student_smjer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Smjer')),
            ],
        ),
        migrations.CreateModel(
            name='SrednjaSkola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_srednje', models.CharField(max_length=100)),
                ('srednja_postanski_broj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto')),
            ],
        ),
        migrations.CreateModel(
            name='Maturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_maturanta', models.CharField(max_length=20)),
                ('prezime_maturanta', models.CharField(max_length=30)),
                ('upisni_broj', models.IntegerField()),
                ('email_maturanta', models.EmailField(blank=True, max_length=70, unique=True)),
                ('maturant_fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fakultet')),
                ('maturant_postanski_broj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto')),
                ('maturant_smjer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Smjer')),
                ('maturant_srednja_skola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SrednjaSkola')),
            ],
        ),
        migrations.AddField(
            model_name='fakultet',
            name='fakultet_sveuciliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sveuciliste'),
        ),
    ]
