# Generated by Django 2.2.12 on 2022-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221212_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjesto',
            name='postanski_broj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='jmbag_studenta',
            field=models.IntegerField(),
        ),
    ]
