# Generated by Django 2.2.12 on 2022-12-13 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221212_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturant',
            name='maturant_datum_upisa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_datum_upisa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
