# Generated by Django 2.2.12 on 2022-12-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_email_studenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_studenta',
            field=models.EmailField(max_length=70),
        ),
    ]
