# Generated by Django 2.2.12 on 2022-12-13 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221213_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kuna',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
