# Generated by Django 2.2.12 on 2022-12-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_student_email_studenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smjer',
            old_name='smjer_fakultet',
            new_name='smjer_fakulteti',
        ),
    ]
