# Generated by Django 2.2.12 on 2022-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20221215_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smjer',
            name='fakulteti',
        ),
        migrations.AddField(
            model_name='fakultet',
            name='smjerovi',
            field=models.ManyToManyField(to='main.Smjer'),
        ),
    ]
