# Generated by Django 2.2.12 on 2022-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221215_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakultet',
            name='smjerovi',
        ),
        migrations.AddField(
            model_name='smjer',
            name='smjer_fakultet',
            field=models.ManyToManyField(to='main.Fakultet'),
        ),
    ]
