# Generated by Django 2.2.12 on 2022-12-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20221215_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smjer',
            old_name='smjer_fakultet',
            new_name='fakulteti',
        ),
    ]
