# Generated by Django 2.2.12 on 2022-12-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221215_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smjer',
            old_name='fakulteti',
            new_name='fakultet',
        ),
    ]
