# Generated by Django 2.2.12 on 2022-12-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20221215_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakultet',
            old_name='naziv_fakulteta',
            new_name='fakultet',
        ),
    ]
