# Generated by Django 2.2.12 on 2022-12-16 22:11

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20221215_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturant',
            name='email_maturanta',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='maturant',
            name='upisni_broj',
            field=models.IntegerField(default=10000, help_text='value 10 000 to 99 999', unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_studenta',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='jmbag_studenta',
            field=models.IntegerField(unique=True, validators=[main.models.validate_10_digits]),
        ),
    ]
