# Generated by Django 2.2.12 on 2023-02-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20230220_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_postanski_broj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Mjesto'),
        ),
    ]
