# Generated by Django 2.2.12 on 2023-02-20 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20230220_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjesto',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mjesto',
            name='postanski_broj',
            field=models.IntegerField(default=10000, help_text='value 10 000 to 99 999', unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_postanski_broj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto'),
        ),
    ]
